version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somephp
       MYSQL_DATABASE: php
       MYSQL_USER: php
       MYSQL_PASSWORD: php

   php:
     depends_on:
       - db
     image: php:7.2-apache
     ports:
       - "8000:80"
     restart: always
     environment:
       PHP_DB_HOST: db:3306
       PHP_DB_USER: php
       PHP_DB_PASSWORD: php
       PHP_DB_NAME: php
volumes:
    db_data: {}
